[application]

[web.app]

# HTML title tag content
title = "ui_main"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/main.css", "assets/start.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
