[package]
name = "llm_requester"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
config = "0.15.13"
log = "0.4.27"
rig-core = "0.17.1"
serde = "1.0.219"
serial_test = "3.2.0"
tokio = { version = "1.47.1", features = ["full"] }
