name: Rust

on:
  push:
    branches:
      ["dev-rust-beyandstars", "dev-rust-doghappy", "dev-rust-horldsence"]
  pull_request:
    branches:
      ["dev-rust-beyandstars", "dev-rust-doghappy", "dev-rust-horldsence"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build ui
        run: cargo build -p ui_main --verbose
      - name: Build terminal
        run: cargo build -p commandline_tool --verbose
