name: Rust

on:
  push:
    branches: ["dev-rust-beyandstars"]
  pull_request:
    branches: ["dev-rust-beyandstars"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -p ui_main --verbose
